const STOPWORDS = new Set(['a','an','and','are','as','at','be','by','for','from','in','is','it','of','on','or','that','the','to','with','au','aux','ce','ces','dans','de','des','du','elle','en','et','il','la','le','les','pour','que','qui','sur','un','une']);
const TOKEN_RE = /[\wÀ-ÿ']+/gu;
let ALL_RECORDS = [];
let SOURCES_INDEX = [];
let SOURCE_LABELS = {};
const SOURCE_ID_ALIASES = {'S-BROLL-JOY-001':'S68','S20':'S72','S35':'S41','S37':'S45','S41-HIST':'S73'};
const FALLBACK_SOURCE_LABELS = {S01:'S01 — Blakeley & Evans, The Regeneration of East Manchester, 2013',S02:'S02 — Sueur, Villes du futur, futur des villes, 2011',S03:'S03 — Demographia, England Largest Cities, s.d.',S04:'S04 — Kidd, Manchester: A History, 2006',S05:'S05 — Jeffery, Tufail & Jackson, Policing and the Reproduction of Local Social Order, 2015',S06:'S06 — Carter, Youth, race and the inner-city estate, 2023',S41:'S41 — Hook, Unknown Pleasures, 2012',S45:'S45 — Curtis, Touching from a Distance, 1995',S46:'S46 — Johnson, An Ideal for Living, 1984',S47:'S47 — West, Joy Division, 1984',S68:'S68 — Broll, Joy Division, 1988',S69:'S69 — Greig & Strong, But We Remember When We Were Young, 2014',S70:'S70 — Suatoni, Dal cuore della città / From the Centre of the City, 1990',S71:'S71 — Flowers, Dreams Never End, 1995/2012',S72:'S72 — Reynolds, Rip It Up and Start Again, 2005/2006',S73:'S73 — Blue Orchids, entrée historique à consolider, s.d.'};
function normalizeSourceId(id){return SOURCE_ID_ALIASES[id] || id}
function flatten(value){if(value===null||value===undefined)return '';if(typeof value==='string')return value;if(typeof value==='number'||typeof value==='boolean')return String(value);if(Array.isArray(value))return value.map(flatten).join(' ');if(typeof value==='object')return Object.entries(value).map(([k,v])=>`${k} ${flatten(v)}`).join(' ');return String(value)}
function tokenize(text){return (text.toLowerCase().match(TOKEN_RE)||[]).filter(t=>t.length>2&&!STOPWORDS.has(t))}
function recordText(record){return [record.id||'',record.kind||'',record.heading||'',record.file||'',flatten(record.data||{})].join('\n').toLowerCase()}
async function loadJson(path,fallback){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return await r.json()}catch(e){console.warn('Fallback',path,e);return fallback||[]}}
async function loadText(path,fallback=''){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path} ${r.status}`);return await r.text()}catch(e){console.warn('Fallback',path,e);return fallback}}
function compactAuthor(author){return String(author||'').replace('Peter Hook','Hook').replace('Deborah Curtis','Curtis').replace('Mike West','West').replace('Marco Broll','Broll').replace('Mark Johnson','Johnson').slice(0,32)}
function compactTitle(title){return String(title||'').replace('Unknown Pleasures: Inside Joy Division','Unknown Pleasures').replace('Touching from a Distance: Ian Curtis and Joy Division','Touching from a Distance').replace('An Ideal for Living: An History of Joy Division','An Ideal for Living').slice(0,48)}
function makeSourceLabel(id,data){const normalized=normalizeSourceId(id);if(data?.source_label)return data.source_label;const author=compactAuthor(data?.auteur||data?.author);const title=compactTitle(data?.titre||data?.title);const year=data?.annee||data?.source_year||'s.d.';const detail=[author,title,year].filter(Boolean).join(', ');return detail?`${normalized} — ${detail}`:(FALLBACK_SOURCE_LABELS[normalized]||normalized)}
function buildSourceLabels(registry,records){const labels={...FALLBACK_SOURCE_LABELS};registry.forEach(entry=>{const id=normalizeSourceId(entry.id||entry.source_id);if(!id)return;labels[id]=makeSourceLabel(id,entry);if(entry.legacy_id){const aliases=Array.isArray(entry.legacy_id)?entry.legacy_id:[entry.legacy_id];aliases.forEach(alias=>labels[alias]=labels[id]);}});records.forEach(record=>{const d=record.data||{};const ids=[];if(d.source_id)ids.push(d.source_id);if(Array.isArray(d.sources))ids.push(...d.sources);ids.forEach(raw=>{const id=normalizeSourceId(raw);if(id&&!labels[id])labels[id]=makeSourceLabel(id,d)})});return labels}
function sourceLabel(sourceId){const normalized=normalizeSourceId(sourceId);return SOURCE_LABELS[normalized] || SOURCE_LABELS[sourceId] || normalized || ''}
function stripMd(value){return String(value||'').trim().replace(/^«\s*/,'').replace(/\s*»$/,'').replace(/`/g,'').replace(/<br\s*\/?>/gi,' | ')}
function splitTableRow(line){return line.trim().replace(/^\|/,'').replace(/\|$/,'').split('|').map(stripMd)}
function inferSourceId(id, sourceCell){const direct=String(id||'').match(/^(S\d{2})-Q\d+/);if(direct)return normalizeSourceId(direct[1]);const fromSource=String(sourceCell||'').match(/S\d{2}(?:-HIST)?/);return fromSource?normalizeSourceId(fromSource[0]):''}
function parseConsolidatedQuotesMarkdown(text){const rows=[];const lines=String(text||'').split(/\r?\n/);let mode='';for(const line of lines){if(line.startsWith('## 1.1.')){mode='historical';continue;}if(line.startsWith('## 2.')){mode='atomized';continue;}if(!line.trim().startsWith('|')||line.includes('---'))continue;const cells=splitTableRow(line);if(!cells.length||/^ID/.test(cells[0])||/^id$/i.test(cells[0]))continue;if(mode==='historical'&&cells.length>=5){const [id,source,type,entry,status]=cells;const sourceId=inferSourceId(id,source);rows.push({kind:'quote',id,file:'registers/quotes/master_quotes.md',heading:'citation historique consolidée',data:{id,source_id:sourceId,source_label:sourceLabel(sourceId),citation_originale:entry,type_citation:type,statut_consolidation:status,statut_verification:status,chapitres:['Chapitre 1'],source_origin:['registre historique','master_quotes.md']}});}else if(mode==='atomized'&&cells.length>=4){const [id,citation,status,usage]=cells;const sourceId=inferSourceId(id,'');rows.push({kind:'quote',id,file:'registers/quotes/master_quotes.md',heading:'citation atomisée consolidée',data:{id,source_id:sourceId,source_label:sourceLabel(sourceId),citation_originale:citation,usage_recommande:usage,statut_consolidation:status,statut_verification:status,source_origin:['atomisation','master_quotes.md']}});}}return rows}
function mergeConsolidatedQuotes(records, consolidated){const existing=new Set(records.map(r=>r.id));const additions=consolidated.filter(r=>!existing.has(r.id));return records.concat(additions)}
function conciseRecord(record){const data=record.data||{};const sourceId=data.source_id ? normalizeSourceId(data.source_id) : data.source_id;const sources=Array.isArray(data.sources)?data.sources.map(normalizeSourceId):data.sources;return {id:record.id,kind:record.kind,file:record.file,heading:record.heading,summary_fields:Object.fromEntries(Object.entries({source_id:sourceId,source_label:data.source_label||sourceLabel(sourceId),source_short_title:data.source_short_title,sources:sources,source_titles:Array.isArray(sources)?sources.map(sourceLabel):undefined,auteur:data.auteur,titre:data.titre,pages_pdf:data.pages_pdf,page_pdf:data.page_pdf,type_unite:data.type_unite,concepts:data.concepts,chapitres:data.chapitres,citation_originale:data.citation_originale,traduction_editoriale_fr:data.traduction_editoriale_fr,usage_recommande:data.usage_recommande,statut_consolidation:data.statut_consolidation,song:data.song,themes:data.themes,name:data.name,role:data.role,date:data.date,event:data.event,certainty:data.certainty}).filter(([,v])=>v!==undefined&&v!==null&&v!==''))}}
function sourceIdsForRecord(record){const ids=[];if(record.data?.source_id)ids.push(normalizeSourceId(record.data.source_id));if(Array.isArray(record.data?.sources)){for(const source of record.data.sources){if(typeof source==='string'&&/^S(\d+|-[A-Z])/.test(source))ids.push(normalizeSourceId(source))}}return [...new Set(ids)]}
function labelCandidate(record){const data=record.data||{};const usefulTitle=data.titre&&!/^S\d+-Q\d+/.test(data.titre)&&!/^S\d+-\d+/.test(data.titre);if(record.id?.endsWith('-000')||data.type_unite==='source'){return {priority:1,titre:data.titre,auteur:data.auteur}}if(record.kind==='atom'&&usefulTitle&&data.auteur){return {priority:2,titre:data.titre,auteur:data.auteur}}if(usefulTitle||data.auteur){return {priority:3,titre:data.titre,auteur:data.auteur}}return null}
function buildSourcesIndex(){const grouped=new Map();for(const record of ALL_RECORDS){const sourceIds=sourceIdsForRecord(record);for(const sourceId of sourceIds){if(!grouped.has(sourceId)){grouped.set(sourceId,{source_id:sourceId,source_label:sourceLabel(sourceId),titre:sourceLabel(sourceId),auteur:'',records:[],counts:{atom:0,quote:0,chronology:0,person:0,song:0,unknown:0}})}const entry=grouped.get(sourceId);entry.records.push(record);entry.counts[record.kind]=(entry.counts[record.kind]||0)+1;const candidate=labelCandidate(record);if(candidate&&!entry.auteur){entry.auteur=candidate.auteur||''}}}SOURCES_INDEX=[...grouped.values()].sort((a,b)=>a.source_id.localeCompare(b.source_id,undefined,{numeric:true}))}
function renderSources(){const container=document.getElementById('sources-list');const count=document.getElementById('sources-count');container.innerHTML='';count.textContent=`${SOURCES_INDEX.length} source(s)`;for(const source of SOURCES_INDEX){const wrapper=document.createElement('div');wrapper.className='source-entry';const button=document.createElement('button');button.innerHTML=`<div class="source-title">${source.source_label}</div><div class="source-meta">${source.counts.atom||0} atomes · ${source.counts.quote||0} citations · ${source.counts.chronology||0} chronologies · ${source.records.length} enregistrements</div>`;button.addEventListener('click',()=>openSource(source.source_id));wrapper.appendChild(button);container.appendChild(wrapper)}}
function openSource(sourceId){const source=SOURCES_INDEX.find(s=>s.source_id===sourceId);if(!source)return;document.getElementById('results-title').textContent=source.source_label;renderResults({total_matches:source.records.length,results:source.records.map(record=>({score:'source',record:conciseRecord(record)}))})}
async function loadCorpus(){const card=document.getElementById('status-card');try{const [records,registry,quotesMd]=await Promise.all([loadJson('../../exports/generated/all_records.json',[]),loadJson('../../data/registre.json',[]),loadText('../../registers/quotes/master_quotes.md','')]);SOURCE_LABELS=buildSourceLabels(registry,records);ALL_RECORDS=mergeConsolidatedQuotes(records,parseConsolidatedQuotesMarkdown(quotesMd));const counts={};for(const record of ALL_RECORDS){const kind=record.kind||'unknown';counts[kind]=(counts[kind]||0)+1}const summary=Object.entries(counts).map(([k,c])=>`${k}: ${c}`).join(' · ');card.textContent=`Corpus chargé · ${ALL_RECORDS.length} enregistrements · ${summary}`;buildSourcesIndex();renderSources()}catch(error){card.textContent=`Erreur : ${error.message}`}}
function clearResults(){document.getElementById('results').innerHTML='';document.getElementById('results-meta').textContent=''}
function addField(dl,key,value){if(value===undefined||value===null||value==='')return;const dt=document.createElement('dt');dt.textContent=key;const dd=document.createElement('dd');dd.textContent=typeof value==='object'?JSON.stringify(value,null,2):value;dl.appendChild(dt);dl.appendChild(dd)}
function renderResults(data){clearResults();const results=document.getElementById('results');const meta=document.getElementById('results-meta');const template=document.getElementById('result-template');meta.textContent=`${data.total_matches} résultat(s)`;if(!data.results.length){const empty=document.createElement('div');empty.className='status-card';empty.textContent='Aucun résultat.';results.appendChild(empty);return}for(const item of data.results){const node=template.content.cloneNode(true);node.querySelector('.result-kind').textContent=item.record.kind;node.querySelector('.result-score').textContent=`${item.score}`;node.querySelector('.result-title').textContent=item.record.id;node.querySelector('.result-file').textContent=item.record.file;const fields=node.querySelector('.result-fields');for(const [key,value] of Object.entries(item.record.summary_fields)){addField(fields,key,value)}results.appendChild(node)}}
function scoreRecords(query,kind){const terms=tokenize(query);if(!terms.length)return [];const results=[];for(const record of ALL_RECORDS){if(kind&&record.kind!==kind)continue;const text=recordText(record);let score=0;for(const term of terms){const matches=text.split(term).length-1;if(matches>0)score+=matches}if(text.includes(query.toLowerCase()))score+=10;if(score>0)results.push({score,record:conciseRecord(record)})}return results.sort((a,b)=>b.score-a.score)}
async function performSearch(query,kind,top){document.getElementById('results-title').textContent='Résultats';const results=document.getElementById('results');results.innerHTML='<div class="status-card">Recherche en cours…</div>';const scored=scoreRecords(query,kind);renderResults({total_matches:scored.length,results:scored.slice(0,Number(top))})}
function bindExamples(){for(const button of document.querySelectorAll('.example-query')){button.addEventListener('click',()=>{const query=button.dataset.query;document.getElementById('query').value=query;performSearch(query,'',10)})}}
function bindForm(){const form=document.getElementById('search-form');form.addEventListener('submit',async event=>{event.preventDefault();const query=document.getElementById('query').value.trim();const kind=document.getElementById('kind').value;const top=document.getElementById('top').value;if(!query)return;await performSearch(query,kind,top)})}
loadCorpus();bindExamples();bindForm();
